---
# file: tasks/install-pip.yml
# Mini installer for pip; only to enable the Ansible `pip` module.
#
# For full installer, use something like:
# 
#  - Stouts.python
#  - bobbyrenwick.pip
#
# @see https://github.com/gmacon/ansible-pip/blob/variable_executables/tasks/main.yml
#

- name: check to see if pip is already installed
  command: "pip --version"
  ignore_errors: true
  register: pip_is_installed

- name: download get-pip.py
  get_url: url=https://bootstrap.pypa.io/get-pip.py  dest=/tmp
  when: pip_is_installed.rc != 0

- name: install pip
  command: "python /tmp/get-pip.py"
  sudo: yes
  when: pip_is_installed.rc != 0

- name: delete get-pip.py
  file: state=absent path=/tmp/get-pip.py
  when: pip_is_installed.rc != 0
