---
# file: tasks/yum-install-python-devel.yml
# Mini installer for python-dev.
#

- name: check default python version
  shell: "python --version 2>&1 | awk '{print $2}'"
  register: python_installed_version

- name: install python-devel
  sudo: True
  yum: name={{ item }}  state=present
  with_items: [ "python-devel", "gcc" ]
  when: python_installed_version.stdout | version_compare('3.0', '<')

#- name: install python3-dev
#  sudo: True
#  apt: name={{ item }}  update_cache=yes  state=present force=yes
#  with_items: [ "python3-dev" ]
#  when: python_installed_version.stdout | version_compare('3.0', '>=')
